services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.32.0
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - ./weaviate_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: 'text2vec-openai,text2vec-cohere,text2vec-huggingface,ref2vec-centroid,generative-openai,qna-openai'
      # This variable is correct for this version, we will keep it
      PERSISTENCE_LSM_ACCESS_STRATEGY_DISK_USE_READONLY_PERCENTAGE: 90
      TZ: Asia/Kolkata
    healthcheck:
      # Use a slightly more robust wget command for the healthcheck
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/v1/.well-known/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.2.1-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # These now point to the service names within the Docker network
      - WEAVIATE_HOST=weaviate
      - REDIS_HOST=redis
      - TZ=Asia/Kolkata
    volumes:
      - ./data:/app/data
      - ./src/agentic_rag:/app/agentic_rag
    depends_on:
      weaviate:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["uvicorn", "agentic_rag.app.api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]


  # A separate service for running the one-off ingestion task
  ingestion-worker:
    build: .
    env_file:
      - .env
    environment:
      - WEAVIATE_HOST=weaviate
      - TZ=Asia/Kolkata
    volumes:
      - ./data:/app/data
      - ./src/agentic_rag:/app/agentic_rag
    depends_on:
      weaviate:
        condition: service_healthy
    # This command runs the ingestion script and then the container exits.
    # In the cloud, this would be a scheduled task.
    command: ["python", "-m", "agentic_rag.scripts.run_ingestion"]

# Define the named volume for Redis persistence
volumes:
  redis_data: