services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.32.0
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - ./weaviate_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: 'text2vec-openai,text2vec-cohere,text2vec-huggingface,ref2vec-centroid,generative-openai,qna-openai'
      # This variable is correct for this version, we will keep it
      PERSISTENCE_LSM_ACCESS_STRATEGY_DISK_USE_READONLY_PERCENTAGE: 90
    healthcheck:
      # Use a slightly more robust wget command for the healthcheck
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/v1/.well-known/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - WEAVIATE_HOST=weaviate
    volumes:
      - ./data:/app/data
      - ./app:/app/app
      - ./config.py:/app/config.py
    depends_on:
      # Re-enable the conditional dependency
      weaviate:
        condition: service_healthy