name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install Poetry
        uses: snok/install-poetry@v1 # <-- USE THIS ACTION
        with:
          version: '2.1.4'

      - name: Install dependencies
        run: poetry install

      - name: Lint with Ruff
        run: poetry run ruff check src/

      - name: Format with Ruff
        run: poetry run ruff format --check src/

      - name: Run Unit Tests with Pytest
        # This step is ready for when you add tests to a tests/ directory
        run: |
          mkdir tests # Placeholder for now
          echo "def test_placeholder(): assert True" > tests/test_smoke.py
          poetry run pytest